Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary2eef04678a2567cb17902c6b850ce753

------WebKitFormBoundary2eef04678a2567cb17902c6b850ce753
Content-Disposition: form-data; name="file"; filename="sample-file.txt"
Content-Type: text/plain

This is a sample file for testing the Forcepoint Inspection API directly via Postman.

------WebKitFormBoundary2eef04678a2567cb17902c6b850ce753--
